apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-dpl
  labels:
    app: mongodb
spec:
  replicas: 2
  selector:
    matchLabels:
      app:mongdb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
      - name: mongodb
        image: mongo
        port:
        - containerPort: 27017
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          valueFrom:
            secretKeyRef:
              name: mod-secret
              key: my-user
        - name: MONGO_INITDB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mod-secret
              key: my-pass